language: php
php:
  - 7.1
  - 7.0
  - 5.6
  - 5.5
  - 5.4
  - 5.3

matrix:
  allow_failures:
    - php: 5.4

before_script:
  - ci/install_extension_for_php_version.sh
  - composer install

script:
  - vendor/bin/phpunit
